### ISSUE TITLE
Pages not updated automatically

### ISSUE THREAD

**Issue by calumapplepie** [palfrey/discord-apt#1]
Pages hasn't updated, so apt isn't seeing the new version

**Comment by palfrey** [comment]
Main [updated fine](https://github.com/palfrey/discord-apt/commit/688a997df30a26a1da5e15089da39b82a569d39e) so the `push` action should have made the pages rebuild. I'll investigate why, but meanwhile [I've manually run the update](https://github.com/palfrey/discord-apt/actions/runs/6232555667/job/16915955318)

**Comment by dmm** [comment]
It looks like the apt repo still has 0.0.30 instead of the new 0.0.31 . Is another manual run needed?

**Comment by palfrey** [comment]
Ah it's a workflow-from-workflow problem (see https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow). I need a new token...

**Comment by palfrey** [comment]
https://github.com/palfrey/discord-apt/commit/2261c8bc1cb8c93234e18726068823bf047e8d8b and related ones before that should fix this now
