### ISSUE TITLE
New version is not published

### ISSUE THREAD

**Issue by cailloumajor** [palfrey/discord-apt#2]
Hello, the latest version 0.0.37 is not available on Discord APT repository. The updating action https://github.com/palfrey/discord-apt/actions/workflows/update.yml is failing since this version was released.

**Comment by palfrey** [comment]
Oh fun. Yeah, I deleted a bunch of older git LFS pieces to stop Github charging me, but apparently that's a bit broken. Right, will poke at that at some point...

**Comment by palfrey** [comment]
I think when I told Github to delete all the old LFS files they must have gotten the 0.0.36 object as well. Oh well, [fixed now](d1d16eb78288eacf22fb0f92ba1201939f1ba510)

**Comment by cailloumajor** [comment]
Thanks!
