### ISSUE TITLE
Angry LFS

### ISSUE THREAD

**Issue by calumapplepie** [palfrey/discord-apt#5]
The most recent workflow run seems to have failed, and discord is not updating.

**Comment by palfrey** [comment]
My LFS quota had apparently run out, which is weird as we're only a week into the month and this is all I use it for. Annoyingly, all Github say is "you've used X GB on discord-apt" not any further breakdown. I've payed the few quid to get another chunk of data plan, but if this happens again this month I won't be doing that.

Hey @discord, feel like chipping in for that? Or say, doing this for yourselves?
