### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by gibbitz** [palfrey/discord-apt#6]
```
|''||''| '||                       '||                                   
   ||     || ..    ....   .. ...    ||  ..     .... ...   ...   ... ...  
   ||     ||' ||  '' .||   ||  ||   || .'       '|.  |  .|  '|.  ||  ||  
   ||     ||  ||  .|' ||   ||  ||   ||'|.        '|.|   ||   ||  ||  ||  
  .||.   .||. ||. '|..'|' .||. ||. .||. ||.       '|     '|..|'  '|..'|. 
                                               .. |                      
                                                ''                       
```
I know this is not what issues are for and you can close this right away, but I wanted to thank you for standing this up. 

As annoying as it was to download remove and reinstall every week it was less effort at one time than doing this, so I didn't. Kudos for having the motivation to do it!

**Comment by palfrey** [comment]
No worries. Took me a while of doing the download dance myself before I had the motivation, but never underestimate the value of being able to actually finally fix something that's annoying you :) I hope one of these days @discord wakes up and does this for themselves though!
